/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The aggregate functions to apply to the fact, this will generate a new column per agg specified, and automatically the agg type to the column name, e.g. column_count, column_sum. "hll" is HyperLogLog (used to approximate count distinct), and "tdigest" is T-Digest (used to approximate percentiles)
 *
 * @minItems 1
 */
export type SchemaColumnAggs = [SchemaColumnAgg, ...SchemaColumnAgg[]];
/**
 * Automatically creates new aggregation columns, "hll" is HyperLogLog (used to approximate count distinct), and "tdigest" is T-Digest (used to approximate percentiles)
 */
export type SchemaColumnAgg =
  | 'count'
  | 'hll'
  | 'max'
  | 'min'
  | 'sum'
  | 'tdigest';
