/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: 'ai_hints' | 'exclude' | 'inherit' | 'local';
    }
)[];

export interface SchemaLightdashDimension {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * SQL statement to determine the dimension
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The time intervals for the lightdash dimension
   */
  time_intervals?:
    | 'OFF'
    | (
        | 'DAY'
        | 'DAY_OF_WEEK_INDEX'
        | 'DAY_OF_WEEK_NAME'
        | 'DAY_OF_MONTH_NUM'
        | 'DAY_OF_YEAR_NUM'
        | 'HOUR'
        | 'MONTH'
        | 'MONTH_NAME'
        | 'MONTH_NUM'
        | 'QUARTER'
        | 'QUARTER_NAME'
        | 'QUARTER_NUM'
        | 'RAW'
        | 'WEEK'
        | 'WEEK_NUM'
        | 'YEAR'
        | 'YEAR_NUM'
      )[];
  type?: 'boolean' | 'date' | 'number' | 'string' | 'timestamp';
  /**
   * The URLs for the lightdash dimension
   */
  urls?: {
    /**
     * The label for the URL
     */
    label: string;
    /**
     * The URL to link to
     */
    url: string;
  }[];
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
