/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate group reference
 */
export type SchemaModelGroup = string;
/**
 * Validate model topic
 */
export type SchemaModelTopic = string;
/**
 * Validate model name
 */
export type SchemaModelName = string;
/**
 * Description for the model that will appear as a hover tooltip in Lightdash
 */
export type SchemaModelDescription = string;
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: 'ai_hints' | 'exclude' | 'inherit' | 'local';
    }
)[];
/**
 * Materialization Configuration
 */
export type SchemaModelMaterialization =
  | 'incremental'
  | 'ephemeral'
  | {
      type: 'ephemeral';
    }
  | {
      type: 'incremental';
      database?: SchemaModelDatabase;
      format?: SchemaModelFormat;
      partitions?: SchemaModelPartitions;
      strategy?: ModelIncrementalStrategySchemaJson;
    };
/**
 * Database override for where the model will be materialized
 */
export type SchemaModelDatabase = string;
/**
 * Open table format for the model
 */
export type SchemaModelFormat = 'delta_lake' | 'hive' | 'iceberg';
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Override the default partitioneds configuration for this model
 */
export type SchemaModelPartitions = SchemaColumnName[];
/**
 * Incremental Strategy
 */
export type ModelIncrementalStrategySchemaJson =
  | {
      type: 'delete+insert';
      /**
       * Override the unique key(s) to use for merging
       */
      unique_key?: string | [string, ...string[]];
      [k: string]: unknown | undefined;
    }
  | {
      type: 'merge';
      /**
       * The unique key(s) to use for merging
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging
       */
      merge_update_columns?: string[];
      [k: string]: unknown | undefined;
    };
/**
 * Type of materialization
 */
export type SchemaModelMaterialized = 'ephemeral' | 'incremental';
/**
 * Override the default partitioned_by configuration for this model
 *
 * @minItems 1
 */
export type SchemaModelPartitionedBy = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Will prevent the automatic date filters from getting added
 */
export type SchemaModelExcludeDateFilter = boolean;
/**
 * Will prevent the automatic portal partition date columns from getting added
 */
export type SchemaModelExcludePortalPartitionColumns = boolean;
/**
 * Will prevent the automatic portal source count column from getting added
 */
export type SchemaModelExcludePortalSourceCount = boolean;
/**
 * Includes the full month when running any given event date
 */
export type ModelIncludeFullMonthSchemaJson = boolean;
/**
 * Use the events dates variable for the partition dates, skipping the dbt_source_dates table mapping
 */
export type ModelUseEventDatesForPartitionDatesSchemaJson = boolean;
/**
 * Validate selecting an existing named column
 */
export type SchemaModelSelectCol =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr?: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: 'dim';
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: 'fct';
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * Description for the selected column
 */
export type SchemaColumnDescription = string;
/**
 * Exclude this dimension from group by when we are aggregating
 */
export type SchemaColumnExcludeFromGroupBy = boolean;
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * Whether this column should be treated as case-sensitive
 */
export type SchemaLightdashCaseSensitive = boolean;
/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Validate Lightdash metric name
 */
export type SchemaLightdashMetricName = string;
/**
 * Validate column data_tests
 */
export type SchemaColumnDataTests = (
  | (
      | 'accepted_values'
      | 'equal_or_lower_row_count'
      | 'equal_row_count'
      | 'no_null_aggregates'
      | 'not_null'
      | 'relationships'
      | 'unique'
    )
  | {
      unique: {
        config: {
          where: SchemaColumnExpr;
        };
      };
    }
  | {
      /**
       * Validates that the SUM of an aggregate column is not NULL for any date partition. This catches partitions where all values are NULL or missing. Use for fact columns in rollup/aggregation models to ensure complete data.
       */
      type: 'no_null_aggregates';
      /**
       * Name of the aggregate column to test (e.g., 'total_amount', 'record_count')
       */
      column_name: string;
      /**
       * Column to use for date filtering. Defaults to 'portal_partition_daily' if not specified.
       */
      date_filter_column?: string;
      /**
       * Data type of the date filter column. Affects how date filtering is applied.
       */
      date_filter_type?: 'date' | 'timestamp' | 'string' | 'number';
    }
  | {
      /**
       * Validates that row count equals parent model (detects unintended 1-to-many relationships). Requires portal_partition_daily column.
       */
      type: 'equal_row_count';
      /**
       * Parent model to compare against. Use ref() syntax, e.g., ref('parent_model_name')
       */
      compare_model: string;
      /**
       * Type of join used (e.g., 'left', 'inner'). Test only runs for specified join types.
       */
      join_type?: string;
    }
  | {
      /**
       * Validates that row count is less than or equal to parent model. Use for joins with filtering conditions. Requires portal_partition_daily column.
       */
      type: 'equal_or_lower_row_count';
      /**
       * Parent model to compare against. Use ref() syntax, e.g., ref('parent_model_name')
       */
      compare_model: string;
      /**
       * Type of join used (e.g., 'left', 'inner'). Optional, for documentation purposes.
       */
      join_type?: string;
    }
)[];
/**
 * Validate selecting a new column using an expression
 */
export type SchemaModelSelectExpr =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: 'dim';
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: 'fct';
    };
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Schema when selecting columns from a source
 */
export type SchemaModelSelectSource =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      source: SchemaRefSourceId;
      data_tests?: SchemaColumnDataTests;
      type?: 'dim' | 'fct';
    }
  | {
      /**
       * @minItems 1
       */
      exclude?: [SchemaColumnName, ...SchemaColumnName[]];
      /**
       * @minItems 1
       */
      include?: [SchemaColumnName, ...SchemaColumnName[]];
      source: SchemaRefSourceId;
      type: 'all_from_source';
    };
/**
 * Validate source ids
 */
export type SchemaRefSourceId = string;
/**
 * SQL WHERE
 */
export type SchemaModelWhere =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
        subquery?: SchemaModelSubquery;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
        subquery?: SchemaModelSubquery;
      }[];
    };

/**
 * Validates schema for staging models selecting from a source
 */
export interface SchemaModelTypeStgSelectSource {
  type: 'stg_select_source';
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  tags?: SchemaModelTags;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  include_full_month?: ModelIncludeFullMonthSchemaJson;
  use_event_dates_for_partition_dates?: ModelUseEventDatesForPartitionDatesSchemaJson;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    )[],
  ];
  from: {
    source: SchemaRefSourceId;
  };
  where?: SchemaModelWhere;
}
/**
 * SQL statements to run before or after models
 */
export interface ModelSqlHooksSchemaJson {
  /**
   * Statement(s) to run after model
   */
  post?: string | [string, ...string[]];
  /**
   * Statement(s) to run before model
   */
  pre?: string | [string, ...string[]];
}
export interface SchemaColumnLightdash {
  case_sensitive?: SchemaLightdashCaseSensitive;
  dimension?: SchemaLightdashDimension;
  /**
   * @minItems 1
   */
  metrics?: [
    (
      | (
          | 'avg'
          | 'count'
          | 'distinctcount'
          | 'max'
          | 'min'
          | 'p50'
          | 'p90'
          | 'p95'
          | 'p98'
          | 'sum'
        )
      | SchemaLightdashMetric
    ),
    ...(
      | (
          | 'avg'
          | 'count'
          | 'distinctcount'
          | 'max'
          | 'min'
          | 'p50'
          | 'p90'
          | 'p95'
          | 'p98'
          | 'sum'
        )
      | SchemaLightdashMetric
    )[],
  ];
  metrics_merge?: SchemaLightdashMetricMerge;
}
export interface SchemaLightdashDimension {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * SQL statement to determine the dimension
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The time intervals for the lightdash dimension
   */
  time_intervals?:
    | 'OFF'
    | (
        | 'DAY'
        | 'DAY_OF_WEEK_INDEX'
        | 'DAY_OF_WEEK_NAME'
        | 'DAY_OF_MONTH_NUM'
        | 'DAY_OF_YEAR_NUM'
        | 'HOUR'
        | 'MONTH'
        | 'MONTH_NAME'
        | 'MONTH_NUM'
        | 'QUARTER'
        | 'QUARTER_NAME'
        | 'QUARTER_NUM'
        | 'RAW'
        | 'WEEK'
        | 'WEEK_NUM'
        | 'YEAR'
        | 'YEAR_NUM'
      )[];
  type?: 'boolean' | 'date' | 'number' | 'string' | 'timestamp';
  /**
   * The URLs for the lightdash dimension
   */
  urls?: {
    /**
     * The label for the URL
     */
    label: string;
    /**
     * The URL to link to
     */
    url: string;
  }[];
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
export interface SchemaLightdashMetric {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: 'thousands' | 'millions' | 'billions' | 'trillions';
  /**
   * The description that will be applied to the column in lightdash
   */
  description?: string;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  name: SchemaLightdashMetricName;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The type of metric
   */
  type:
    | 'average'
    | 'boolean'
    | 'count'
    | 'count_distinct'
    | 'date'
    | 'max'
    | 'median'
    | 'min'
    | 'number'
    | 'percentile'
    | 'string'
    | 'sum';
}
/**
 * Values that can be merged in to override values on a metric
 */
export interface SchemaLightdashMetricMerge {
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: 'thousands' | 'millions' | 'billions' | 'trillions';
  /**
   * The description that will be applied to the metric in lightdash
   */
  description?: string;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  round?: number;
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
}
export interface SchemaModelSelectInterval {
  description?: SchemaColumnDescription;
  interval: 'day' | 'hour' | 'month' | 'year';
  lightdash?: SchemaColumnLightdash;
  model?: SchemaModelRef;
  name: 'datetime';
  data_tests?: SchemaColumnDataTests;
  type?: 'dim';
}
/**
 * Defines an inline subquery for use in WHERE or HAVING conditions. Supports IN, NOT IN, EXISTS, NOT EXISTS, and scalar comparison operators.
 */
export interface SchemaModelSubquery {
  /**
   * How the subquery result is compared against the column
   */
  operator:
    | 'in'
    | 'not_in'
    | 'exists'
    | 'not_exists'
    | 'eq'
    | 'neq'
    | 'gt'
    | 'gte'
    | 'lt'
    | 'lte';
  /**
   * Column to compare against the subquery result. Required for all operators except exists/not_exists.
   */
  column?: string;
  /**
   * Columns or expressions to select in the subquery
   *
   * @minItems 1
   */
  select: [string, ...string[]];
  /**
   * Data source for the subquery
   */
  from:
    | {
        model: SchemaModelRef;
      }
    | {
        source: SchemaRefSourceId;
      }
    | {
        /**
         * Reference to a CTE defined in the ctes array
         */
        cte: string;
      };
  where?: SchemaModelWhere;
}
