/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate model order by
 *
 * @minItems 1
 */
export type SchemaModelOrderBy = [
  (
    | SchemaColumnName
    | {
        name?: SchemaColumnName;
        type?: 'asc' | 'desc';
      }
  ),
  ...(
    | SchemaColumnName
    | {
        name?: SchemaColumnName;
        type?: 'asc' | 'desc';
      }
  )[],
];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
