/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rollup configuration for time-grain re-aggregation
 */
export interface SchemaModelFromRollup {
  datetime_expr?: string;
  /**
   * The interval for the rollup
   */
  interval: 'day' | 'hour' | 'month' | 'year';
}
