/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL WHERE
 */
export type SchemaModelWhere =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
        subquery?: SchemaModelSubquery;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
        subquery?: SchemaModelSubquery;
      }[];
    };
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * SQL WHERE
 */
export type SchemaModelWhere1 =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
        subquery?: SchemaModelSubquery;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
        subquery?: SchemaModelSubquery;
      }[];
    };
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Validate source ids
 */
export type SchemaRefSourceId = string;

/**
 * Defines an inline subquery for use in WHERE or HAVING conditions. Supports IN, NOT IN, EXISTS, NOT EXISTS, and scalar comparison operators.
 */
export interface SchemaModelSubquery {
  /**
   * How the subquery result is compared against the column
   */
  operator:
    | 'in'
    | 'not_in'
    | 'exists'
    | 'not_exists'
    | 'eq'
    | 'neq'
    | 'gt'
    | 'gte'
    | 'lt'
    | 'lte';
  /**
   * Column to compare against the subquery result. Required for all operators except exists/not_exists.
   */
  column?: string;
  /**
   * Columns or expressions to select in the subquery
   *
   * @minItems 1
   */
  select: [string, ...string[]];
  /**
   * Data source for the subquery
   */
  from:
    | {
        model: SchemaModelRef;
      }
    | {
        source: SchemaRefSourceId;
      }
    | {
        /**
         * Reference to a CTE defined in the ctes array
         */
        cte: string;
      };
  where?: SchemaModelWhere1;
}
