/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;

/**
 * Validates the join argument when joining to a column
 */
export interface SchemaModelFromJoinColumn {
  type?: 'cross_join_unnest';
  column: SchemaColumnExpr;
  /**
   * @minItems 1
   */
  fields: [SchemaColumnExpr, ...SchemaColumnExpr[]];
}
