/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates the join argument when joining multiple models or CTEs
 *
 * @minItems 1
 */
export type SchemaModelFromJoinModels = [
  (
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        on:
          | 'dims'
          | {
              /**
               * Conditions to be combined by AND
               */
              and?: (
                | SchemaColumnName
                | {
                    /**
                     * SQL for the condition
                     */
                    expr: string;
                  }
                | {
                    subquery: SchemaModelSubquery;
                  }
              )[];
            };
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        on:
          | 'dims'
          | {
              /**
               * Conditions to be combined by AND
               */
              and?: (
                | SchemaColumnName
                | {
                    /**
                     * SQL for the condition
                     */
                    expr: string;
                  }
                | {
                    subquery: SchemaModelSubquery;
                  }
              )[];
            };
      }
  ),
  ...(
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        on:
          | 'dims'
          | {
              /**
               * Conditions to be combined by AND
               */
              and?: (
                | SchemaColumnName
                | {
                    /**
                     * SQL for the condition
                     */
                    expr: string;
                  }
                | {
                    subquery: SchemaModelSubquery;
                  }
              )[];
            };
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        on:
          | 'dims'
          | {
              /**
               * Conditions to be combined by AND
               */
              and?: (
                | SchemaColumnName
                | {
                    /**
                     * SQL for the condition
                     */
                    expr: string;
                  }
                | {
                    subquery: SchemaModelSubquery;
                  }
              )[];
            };
      }
  )[],
];
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Validate source ids
 */
export type SchemaRefSourceId = string;
/**
 * SQL WHERE
 */
export type SchemaModelWhere =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
        subquery?: SchemaModelSubquery;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
        subquery?: SchemaModelSubquery;
      }[];
    };
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;

/**
 * Defines an inline subquery for use in WHERE or HAVING conditions. Supports IN, NOT IN, EXISTS, NOT EXISTS, and scalar comparison operators.
 */
export interface SchemaModelSubquery {
  /**
   * How the subquery result is compared against the column
   */
  operator:
    | 'in'
    | 'not_in'
    | 'exists'
    | 'not_exists'
    | 'eq'
    | 'neq'
    | 'gt'
    | 'gte'
    | 'lt'
    | 'lte';
  /**
   * Column to compare against the subquery result. Required for all operators except exists/not_exists.
   */
  column?: string;
  /**
   * Columns or expressions to select in the subquery
   *
   * @minItems 1
   */
  select: [string, ...string[]];
  /**
   * Data source for the subquery
   */
  from:
    | {
        model: SchemaModelRef;
      }
    | {
        source: SchemaRefSourceId;
      }
    | {
        /**
         * Reference to a CTE defined in the ctes array
         */
        cte: string;
      };
  where?: SchemaModelWhere;
}
