/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates the join argument when joining multiple models or CTEs
 *
 * @minItems 1
 */
export type SchemaModelFromJoinModels = [
  (
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
  ),
  ...(
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'cross';
      }
    | {
        /**
         * Name of a CTE defined in the ctes array
         */
        cte: string;
        override_alias?: SchemaColumnName;
        type?: 'full' | 'inner' | 'left' | 'right';
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
  )[],
];
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Validate column name
 */
export type SchemaColumnName = string;
