/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Materialization Configuration
 */
export type SchemaModelMaterialization =
  | 'incremental'
  | 'ephemeral'
  | {
      type: 'ephemeral';
    }
  | {
      type: 'incremental';
      database?: SchemaModelDatabase;
      format?: SchemaModelFormat;
      partitions?: SchemaModelPartitions;
      strategy?: IncrementalStrategy;
    };
/**
 * Database override for where the model will be materialized
 */
export type SchemaModelDatabase = string;
/**
 * Open table format for the model
 */
export type SchemaModelFormat = 'delta_lake' | 'hive' | 'iceberg';
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Override the default partitioneds configuration for this model
 */
export type SchemaModelPartitions = SchemaColumnName[];
/**
 * Incremental Strategy for dbt-trino. Pick one of: 'append', 'delete+insert', 'merge', 'overwrite_existing_partitions'. NOTE: 'overwrite_existing_partitions' requires a custom dbt macro in your project and is not shipped by the DJ extension. 'merge' requires the target table to use Iceberg format in dbt-trino. When in doubt, use 'delete+insert' with a partition column as unique_key.
 */
export type IncrementalStrategy =
  | {
      /**
       * Append rows without de-duplication.
       */
      type: 'append';
    }
  | {
      /**
       * Delete rows matching unique_key, then insert.
       */
      type: 'delete+insert';
      /**
       * Override the unique key(s) to use for delete+insert. Defaults to the model's partition column when omitted.
       */
      unique_key?: string | [string, ...string[]];
    }
  | {
      /**
       * Row-level upsert on unique_key. Requires Iceberg in dbt-trino.
       */
      type: 'merge';
      /**
       * The unique key(s) to use for merging.
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging.
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging.
       */
      merge_update_columns?: string[];
    }
  | {
      /**
       * Overwrite only the partitions in the new slice. REQUIRES a custom macro in your dbt project — prefer 'delete+insert' if you do not have one.
       */
      type: 'overwrite_existing_partitions';
      /**
       * Optional override for the unique key(s). Defaults to the model's partition column when omitted.
       */
      unique_key?: string | [string, ...string[]];
    };
