/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate model group by
 *
 * @minItems 1
 */
export type SchemaModelGroupBy = [
  (
    | string
    | {
        expr: string;
      }
    | {
        type: 'dims';
      }
  ),
  ...(
    | string
    | {
        expr: string;
      }
    | {
        type: 'dims';
      }
  )[],
];
