/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for using a table function to query this source
 */
export interface SchemaSourceTableFunction {
  /**
   * The table function argument name
   */
  arg: string;
  /**
   * The database (catalog) of the table function
   */
  database: string;
  /**
   * The schema of the table function
   */
  dialect: 'bigquery';
  /**
   * The ref for the source table we are selecting from inside the table function
   */
  from?: string;
  /**
   * The name of the table function
   */
  name: string;
  /**
   * The schema of the table function
   */
  schema: string;
}
