/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * The expression to use to extract the event datetime
 */
export type SchemaColumnExpr = string;

/**
 * Configuration for determining the event date when querying this source
 */
export interface SchemaSourceEventDatetime {
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr;
  /**
   * Whether or not to use a range for the event date filter instead of a list
   */
  use_range?: boolean;
}
