/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Source ETL settings
 */
export type SchemaSourceEtl =
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * The date from which to start backfilling all downstream models
       */
      backfill_start: string;
      /**
       * An expression to be used as a query cursor for determining which event dates have changed since last time the etl was run
       */
      cursor_expr?: string;
      /**
       * The number of days to lookback when querying the source
       */
      lookback_days?: number;
      /**
       * SQL statement which will determine if certain source event dates should be included event if their event_count didn't change, the query should return two columns, event_date and updated_timestamp
       */
      sql_event_date_updated_timestamps?: string;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'event_count';
    }
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'run_schedule';
    };
