/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configures dbt freshness settings for this source
 */
export interface SchemaSourceFreshness {
  error_after?: {
    /**
     * A positive integer for the number of periods where a data source is still considered fresh
     */
    count: number;
    /**
     * The time period used in the freshness calculation
     */
    period: 'day' | 'hour' | 'minute';
  };
  /**
   * Add a where clause to the query run by dbt source freshness in order to limit data scanned
   */
  filter?: string;
  warn_after?: {
    /**
     * A positive integer for the number of periods where a data source is still considered fresh
     */
    count: number;
    /**
     * The time period used in the freshness calculation
     */
    period: 'day' | 'hour' | 'minute';
  };
}
