/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configuration for partitions to use when querying this source
 */
export type SchemaSourcePartition =
  | {
      data_type?: SchemaColumnDataType;
      dialect?: SchemaColumnDataType;
      expr: SchemaColumnExpr;
      /**
       * The interval used for partitioning, this will be used to determine the partition date range
       */
      interval?: 'day' | 'month';
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'event_dates';
      /**
       * Whether or not to use a range for the partition date filter instead of a list
       */
      use_range?: boolean;
    }
  | {
      data_type?: SchemaColumnDataType;
      expr: SchemaColumnExpr1;
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'neq';
      /**
       * The value to compare the partition field to
       */
      value?: string;
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr = string;
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr1 = string;
