/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A column name (or expression) that returns a timestamp indicating freshness
 */
export type SchemaLoadedAtField = string;
/**
 * Source ETL settings
 */
export type SchemaSourceEtl =
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * The date from which to start backfilling all downstream models
       */
      backfill_start: string;
      /**
       * An expression to be used as a query cursor for determining which event dates have changed since last time the etl was run
       */
      cursor_expr?: string;
      /**
       * The number of days to lookback when querying the source
       */
      lookback_days?: number;
      /**
       * SQL statement which will determine if certain source event dates should be included event if their event_count didn't change, the query should return two columns, event_date and updated_timestamp
       */
      sql_event_date_updated_timestamps?: string;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'event_count';
    }
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'run_schedule';
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * The expression to use to extract the event datetime
 */
export type SchemaColumnExpr = string;
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr1 = string;
/**
 * Configuration for partitions to use when querying this source
 */
export type SchemaSourcePartition =
  | {
      data_type?: SchemaColumnDataType;
      dialect?: SchemaColumnDataType;
      expr: SchemaColumnExpr2;
      /**
       * The interval used for partitioning, this will be used to determine the partition date range
       */
      interval?: 'day' | 'month';
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'event_dates';
      /**
       * Whether or not to use a range for the partition date filter instead of a list
       */
      use_range?: boolean;
    }
  | {
      data_type?: SchemaColumnDataType;
      expr: SchemaColumnExpr3;
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'neq';
      /**
       * The value to compare the partition field to
       */
      value?: string;
    };
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr2 = string;
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr3 = string;
/**
 * Overrides the default portal partition columns for any model directly downstream of this source
 *
 * @minItems 1
 */
export type SchemaSourcePortalPartitionColumns = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * The where clause expression
 */
export type SchemaColumnExpr4 = string;
/**
 * Description for the selected column
 */
export type SchemaColumnDescription = string;
/**
 * Whether this column should be treated as case-sensitive
 */
export type SchemaLightdashCaseSensitive = boolean;
/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: 'ai_hints' | 'exclude' | 'inherit' | 'local';
    }
)[];
/**
 * Validate Lightdash metric name
 */
export type SchemaLightdashMetricName = string;
/**
 * Validate column type
 */
export type SchemaColumnType = 'dim' | 'fct';

/**
 * Table configuration for this source
 */
export interface SchemaSourceTable {
  /**
   * The name of the table
   */
  name: string;
  /**
   * A description for the table
   */
  description?: string;
  freshness?: SchemaSourceFreshness | null;
  loaded_at_field?: SchemaLoadedAtField;
  meta?: SchemaSourceMeta;
  /**
   * An array of columns which exist on the table
   */
  columns: {
    /**
     * The column data type from Trino, we don't validate this specifically in the framework schema as many combinations are possible
     */
    data_type: string;
    description?: SchemaColumnDescription;
    lightdash?: SchemaColumnLightdash;
    name: SchemaColumnName;
    type?: SchemaColumnType;
  }[];
}
/**
 * Configures dbt freshness settings for this source
 */
export interface SchemaSourceFreshness {
  error_after?: {
    /**
     * A positive integer for the number of periods where a data source is still considered fresh
     */
    count: number;
    /**
     * The time period used in the freshness calculation
     */
    period: 'day' | 'hour' | 'minute';
  };
  /**
   * Add a where clause to the query run by dbt source freshness in order to limit data scanned
   */
  filter?: string;
  warn_after?: {
    /**
     * A positive integer for the number of periods where a data source is still considered fresh
     */
    count: number;
    /**
     * The time period used in the freshness calculation
     */
    period: 'day' | 'hour' | 'minute';
  };
}
/**
 * Validates schema for source meta (either on the schema or table level)
 */
export interface SchemaSourceMeta {
  etl?: SchemaSourceEtl;
  event_datetime?: SchemaSourceEventDatetime;
  partition_date?: SchemaSourcePartitionDate;
  partitions?: SchemaSourcePartition[];
  portal_partition_columns?: SchemaSourcePortalPartitionColumns;
  portal_source_count?: SchemaSourcePortalSourceCount;
  table_function?: SchemaSourceTableFunction;
  where?: SchemaSourceWhere;
}
/**
 * Configuration for determining the event date when querying this source
 */
export interface SchemaSourceEventDatetime {
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr;
  /**
   * Whether or not to use a range for the event date filter instead of a list
   */
  use_range?: boolean;
}
/**
 * Configuration for determining the partition date when querying this source
 */
export interface SchemaSourcePartitionDate {
  /**
   * Whether or not to fetch the patition dates at compile time instead of runtime, this is true by default as it can significantly improve partitioning performance
   */
  compile_dates?: boolean;
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr1;
  /**
   * The interval used for partitioning, this will be used to determine the partition date range
   */
  interval?: 'day' | 'month';
  /**
   * Whether or not to use the event dates as the partition dates
   */
  use_event_dates?: boolean;
  /**
   * Whether or not to use a range for the partition date filter instead of a list
   */
  use_range?: boolean;
}
/**
 * Overrides any default settings for the portal_source_count column
 */
export interface SchemaSourcePortalSourceCount {
  /**
   * Explicitly exclude a portal_source_count column for this source
   */
  exclude?: boolean;
  /**
   * Custom label for the portal source count metric
   */
  metric_label?: string;
}
/**
 * Configuration for using a table function to query this source
 */
export interface SchemaSourceTableFunction {
  /**
   * The table function argument name
   */
  arg: string;
  /**
   * The database (catalog) of the table function
   */
  database: string;
  /**
   * The schema of the table function
   */
  dialect: 'bigquery';
  /**
   * The ref for the source table we are selecting from inside the table function
   */
  from?: string;
  /**
   * The name of the table function
   */
  name: string;
  /**
   * The schema of the table function
   */
  schema: string;
}
/**
 * Applys a static "where" clause any time this source is queried
 */
export interface SchemaSourceWhere {
  expr: SchemaColumnExpr4;
}
export interface SchemaColumnLightdash {
  case_sensitive?: SchemaLightdashCaseSensitive;
  dimension?: SchemaLightdashDimension;
  /**
   * @minItems 1
   */
  metrics?: [
    (
      | (
          | 'avg'
          | 'count'
          | 'distinctcount'
          | 'max'
          | 'min'
          | 'p50'
          | 'p90'
          | 'p95'
          | 'p98'
          | 'sum'
        )
      | SchemaLightdashMetric
    ),
    ...(
      | (
          | 'avg'
          | 'count'
          | 'distinctcount'
          | 'max'
          | 'min'
          | 'p50'
          | 'p90'
          | 'p95'
          | 'p98'
          | 'sum'
        )
      | SchemaLightdashMetric
    )[],
  ];
  metrics_merge?: SchemaLightdashMetricMerge;
}
export interface SchemaLightdashDimension {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * SQL statement to determine the dimension
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The time intervals for the lightdash dimension
   */
  time_intervals?:
    | 'OFF'
    | (
        | 'DAY'
        | 'DAY_OF_WEEK_INDEX'
        | 'DAY_OF_WEEK_NAME'
        | 'DAY_OF_MONTH_NUM'
        | 'DAY_OF_YEAR_NUM'
        | 'HOUR'
        | 'MONTH'
        | 'MONTH_NAME'
        | 'MONTH_NUM'
        | 'QUARTER'
        | 'QUARTER_NAME'
        | 'QUARTER_NUM'
        | 'RAW'
        | 'WEEK'
        | 'WEEK_NUM'
        | 'YEAR'
        | 'YEAR_NUM'
      )[];
  type?: 'boolean' | 'date' | 'number' | 'string' | 'timestamp';
  /**
   * The URLs for the lightdash dimension
   */
  urls?: {
    /**
     * The label for the URL
     */
    label: string;
    /**
     * The URL to link to
     */
    url: string;
  }[];
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
export interface SchemaLightdashMetric {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: 'thousands' | 'millions' | 'billions' | 'trillions';
  /**
   * The description that will be applied to the column in lightdash
   */
  description?: string;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  name: SchemaLightdashMetricName;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The type of metric
   */
  type:
    | 'average'
    | 'boolean'
    | 'count'
    | 'count_distinct'
    | 'date'
    | 'max'
    | 'median'
    | 'min'
    | 'number'
    | 'percentile'
    | 'string'
    | 'sum';
}
/**
 * Values that can be merged in to override values on a metric
 */
export interface SchemaLightdashMetricMerge {
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: 'thousands' | 'millions' | 'billions' | 'trillions';
  /**
   * The description that will be applied to the metric in lightdash
   */
  description?: string;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  round?: number;
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
}
