/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Source ETL settings
 */
export type SchemaSourceEtl =
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * The date from which to start backfilling all downstream models
       */
      backfill_start: string;
      /**
       * An expression to be used as a query cursor for determining which event dates have changed since last time the etl was run
       */
      cursor_expr?: string;
      /**
       * The number of days to lookback when querying the source
       */
      lookback_days?: number;
      /**
       * SQL statement which will determine if certain source event dates should be included event if their event_count didn't change, the query should return two columns, event_date and updated_timestamp
       */
      sql_event_date_updated_timestamps?: string;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'event_count';
    }
  | {
      /**
       * Whether or not this source should be checked when the ETL runs
       */
      active: boolean;
      /**
       * SQL statement which will be run before a retry if the first attempt to query the source dates fails
       */
      sql_retry?: string;
      type?: 'run_schedule';
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * The expression to use to extract the event datetime
 */
export type SchemaColumnExpr = string;
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr1 = string;
/**
 * Configuration for partitions to use when querying this source
 */
export type SchemaSourcePartition =
  | {
      data_type?: SchemaColumnDataType;
      dialect?: SchemaColumnDataType;
      expr: SchemaColumnExpr2;
      /**
       * The interval used for partitioning, this will be used to determine the partition date range
       */
      interval?: 'day' | 'month';
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'event_dates';
      /**
       * Whether or not to use a range for the partition date filter instead of a list
       */
      use_range?: boolean;
    }
  | {
      data_type?: SchemaColumnDataType;
      expr: SchemaColumnExpr3;
      /**
       * The type of partition to use (event_dates will build a list for comparison to the project event dates variable)
       */
      type: 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'neq';
      /**
       * The value to compare the partition field to
       */
      value?: string;
    };
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr2 = string;
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr3 = string;
/**
 * Overrides the default portal partition columns for any model directly downstream of this source
 *
 * @minItems 1
 */
export type SchemaSourcePortalPartitionColumns = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * The where clause expression
 */
export type SchemaColumnExpr4 = string;

/**
 * Validates schema for source meta (either on the schema or table level)
 */
export interface SchemaSourceMeta {
  etl?: SchemaSourceEtl;
  event_datetime?: SchemaSourceEventDatetime;
  partition_date?: SchemaSourcePartitionDate;
  partitions?: SchemaSourcePartition[];
  portal_partition_columns?: SchemaSourcePortalPartitionColumns;
  portal_source_count?: SchemaSourcePortalSourceCount;
  table_function?: SchemaSourceTableFunction;
  where?: SchemaSourceWhere;
}
/**
 * Configuration for determining the event date when querying this source
 */
export interface SchemaSourceEventDatetime {
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr;
  /**
   * Whether or not to use a range for the event date filter instead of a list
   */
  use_range?: boolean;
}
/**
 * Configuration for determining the partition date when querying this source
 */
export interface SchemaSourcePartitionDate {
  /**
   * Whether or not to fetch the patition dates at compile time instead of runtime, this is true by default as it can significantly improve partitioning performance
   */
  compile_dates?: boolean;
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr1;
  /**
   * The interval used for partitioning, this will be used to determine the partition date range
   */
  interval?: 'day' | 'month';
  /**
   * Whether or not to use the event dates as the partition dates
   */
  use_event_dates?: boolean;
  /**
   * Whether or not to use a range for the partition date filter instead of a list
   */
  use_range?: boolean;
}
/**
 * Overrides any default settings for the portal_source_count column
 */
export interface SchemaSourcePortalSourceCount {
  /**
   * Explicitly exclude a portal_source_count column for this source
   */
  exclude?: boolean;
  /**
   * Custom label for the portal source count metric
   */
  metric_label?: string;
}
/**
 * Configuration for using a table function to query this source
 */
export interface SchemaSourceTableFunction {
  /**
   * The table function argument name
   */
  arg: string;
  /**
   * The database (catalog) of the table function
   */
  database: string;
  /**
   * The schema of the table function
   */
  dialect: 'bigquery';
  /**
   * The ref for the source table we are selecting from inside the table function
   */
  from?: string;
  /**
   * The name of the table function
   */
  name: string;
  /**
   * The schema of the table function
   */
  schema: string;
}
/**
 * Applys a static "where" clause any time this source is queried
 */
export interface SchemaSourceWhere {
  expr: SchemaColumnExpr4;
}
