/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Overrides the default portal partition columns for any model directly downstream of this source
 *
 * @minItems 1
 */
export type SchemaSourcePortalPartitionColumns = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
