/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | 'bigint'
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'double'
  | 'integer'
  | 'number'
  | 'row(date)'
  | 'row(varchar)'
  | 'string'
  | 'timestamp'
  | 'timestamp(0)'
  | 'timestamp(3)'
  | 'timestamp(6)'
  | 'varchar';
/**
 * The expression to use to determine the partition date, be careful not to cast here as that will prevent partition pruning
 */
export type SchemaColumnExpr = string;

/**
 * Configuration for determining the partition date when querying this source
 */
export interface SchemaSourcePartitionDate {
  /**
   * Whether or not to fetch the patition dates at compile time instead of runtime, this is true by default as it can significantly improve partitioning performance
   */
  compile_dates?: boolean;
  data_type?: SchemaColumnDataType;
  expr: SchemaColumnExpr;
  /**
   * The interval used for partitioning, this will be used to determine the partition date range
   */
  interval?: 'day' | 'month';
  /**
   * Whether or not to use the event dates as the partition dates
   */
  use_event_dates?: boolean;
  /**
   * Whether or not to use a range for the partition date filter instead of a list
   */
  use_range?: boolean;
}
