jaffle_shop_lightdash:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: dbt_user
      password: '' # Empty password for no authentication
      host: localhost
      port: 8080
      database: development # database instead of catalog for Lightdash compatibility
      schema: jaffle_shop_lightdash_dev
      threads: 4
      http_scheme: http
